#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Editor
#
# export TERM='screen-256color'
tic -x -o ~/.terminfo ~/xterm-24bit.terminfo
export TERM=xterm-24bit

# ssh truecolor support https://github.com/syl20bnr/spacemacs/wiki/Terminal
alias ssh="TERM=xterm-256color ssh"

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='emacsclient -t'
export VISUAL='emacsclient -t'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
fi

#
# Paths
#

export KUBECONFIG=$KUBECONFIG:~/.kube/config

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ~/.local/bin
  /usr/local/{bin,sbin}
  ~/bin
  ~/.yarn/bin
  ~/src/devops/bin
  /snap/bin
  /usr/lib/x86_64-linux-gnu/pkgconfig
  $path
)

#
# NVM
#
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# k8s
#
alias k=kubectl
export KUBECONFIG=$KUBECONFIG:~/.kube/config-citizennet-nonprod

#
# Make
#
export RTS_ARGS='+RTS -N2 -A800m -RTS'
function m () {
    local ARGS=$@
    echo "time (make $ARGS)"
    time (make $ARGS)
}

#
# Nix
#
source ~/.nix-profile/etc/profile.d/nix.sh
eval "$(direnv hook zsh)"
